### ISSUE TITLE
flutter_youtube_player: ^1.0.0 doesn't support in dart 3.2.2

### ISSUE THREAD

**Issue by RaddN** [shoyabsiddique/youtube_video_player#1]
The current Dart SDK version is 3.2.2.

Because ictexpert depends on flutter_youtube_player >=0.0.2 which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.1.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

**Comment by shoyabsiddique0** [comment]
Have you tried the latest version?

**Comment by RaddN** [comment]
flutter_youtube_player: ^1.0.0 used this

**Comment by RaddN** [comment]
solved thanks
